### ISSUE TITLE
[개선 사항] 필터 항목 변경됨

### ISSUE THREAD

**Issue by JeongbinYoon** [dnwn-9001/react-todolist#1]
<img width="488" alt="스크린샷 2024-11-12 오후 9 08 28" src="https://github.com/user-attachments/assets/f84456f1-4546-42dc-87a4-fc911a47a334">

- 미완료 필터에서 완료 눌렀을 때 전체 필터 처럼 완료항목도 노출이 됩니다.
- 제목과 내용이 꼭 있어야 한다는 의도라면 trim()사용해서 공백 체크 해도 좋을 것 같아요.
- 항목 여백은 일정하면 좋을 것 같습니다!

**Comment by dnwn-9001** [comment]
모두 수정해서 반영했습니다 :)!!
