### ISSUE TITLE
[개선사항] 완료 혹은 미완료로 리스트 필터 후 새로운 todo 등록시

### ISSUE THREAD

**Issue by JangHyunjeong** [dnwn-9001/react-todolist#3]
![image](https://github.com/user-attachments/assets/eac2098c-2ba1-4b49-90d0-0dceed03819b)

- 완료 혹은 미완료로 리스트 필터 후 새로운 todo 등록시, 
필터는 완료 혹은 미완료 상태로 전체 todoList 가 노출됩니다.

**Comment by dnwn-9001** [comment]
추가 등록 시 필터값(완료/미완료)과 상태별 필터링 유지하도록 수정했습니다! :)
