### ISSUE TITLE
[제안] 파일 형식, 공통 UI 컴포넌트화

### ISSUE THREAD

**Issue by hansololiviakim** [dnwn-9001/react-todolist#6]
투두는 세로 형식을 많이 봤는데 가로로 나뉘어져 있으니 한 눈에 들어와서 파악하기 좋았어요! 분홍색 색감도 마음에 들어요🥰

파일 명의 경우 UI 포함 로직을 리턴하는 부분이 .js로 되어 있는데, 저라면 .jsx로 해두었을 것 같습니다! 둘의 차이는 로직에 UI를 포함해서 리턴하냐의 여부인데 파일 형식만 보고도 이 파일은 화면요소를 포함하고 있구나/단순 로직만 리턴하는구나를 다른 개발자가 파악하기 쉽기 때문입니다ㅎㅎ 변수명이나 파일명, 파일형식으로도 읽기 쉬운 코드를 만들 수 있다고 생각해서 저는 그렇게 하는 편입니다!

저도 isDone && ~ 하는 부분 추상화해서 공통 컴포넌트로 빼야 하는데 영인님 코드 보고 생각나서 같이 적어둡니다.. 잊지 말기..ㅁ7ㅁ8

**Comment by dnwn-9001** [comment]
의견 감사합니다 ! 확장자 변경 완료했습니다 :)
